# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vistaordine.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

import imaginOrdine

class VistaListaOrdini(QWidget):
    def __init__(self, parent=None):
        super(VistaListaOrdini, self).__init__()

        self.setObjectName("VistaListaOrdini")
        self.resize(730, 600)
        self.setMinimumSize(QtCore.QSize(730, 600))
        self.setMaximumSize(QtCore.QSize(730, 600))

        self.sfondoOrdine = QtWidgets.QLabel(self)
        self.sfondoOrdine.setGeometry(QtCore.QRect(0, 0, 730, 600))
        self.sfondoOrdine.setText("")
        self.sfondoOrdine.setPixmap(QtGui.QPixmap(":/newPrefix/imgOrdine.jpg"))
        self.sfondoOrdine.setScaledContents(True)
        self.sfondoOrdine.setObjectName("sfondoOrdine")

        self.listView = QtWidgets.QListView(self)
        self.listView.setGeometry(QtCore.QRect(30, 40, 571, 521))
        self.listView.setObjectName("listView")

        self.ButtonApri = QtWidgets.QPushButton(self)
        self.ButtonApri.setGeometry(QtCore.QRect(610, 40, 111, 70))
        self.ButtonApri.setStyleSheet("QPushButton#ButtonApri{\n"
                                        "  background-color:#293d3d;\n"
                                        "  border-radius: 30px;\n"
                                        "  color: white;\n"
                                        "  padding: 16px 32px;\n"
                                        "  text-align: center;\n"
                                        "  text-decoration: none;\n"
                                        "  display: inline-block;\n"
                                        "  font-size: 16px;\n"
                                        "  margin: 4px 2px;\n"
                                        "  transition-duration: 0.4s;\n"
                                        "  cursor: pointer;\n"
                                        "}\n"
                                        "QPushButton#ButtonApri:pressed{\n"
                                        " background-color: white; \n"
                                        "  color: black; \n"
                                        "  border: 3px solid #4CAF50;\n"
                                        "}\n"
                                        "QPushButton#ButtonApri:hover {background-color:      #d1e0e0;}")
        self.ButtonApri.setObjectName("ButtonApri")
        self.ButtonHome = QtWidgets.QPushButton(self)
        self.ButtonHome.setGeometry(QtCore.QRect(610, 180, 111, 70))
        self.ButtonHome.setStyleSheet("QPushButton#ButtonHome{\n"
                                        "  background-color:#293d3d;\n"
                                        "  border-radius: 30px;\n"
                                        "  color: white;\n"
                                        "  padding: 16px 32px;\n"
                                        "  text-align: center;\n"
                                        "  text-decoration: none;\n"
                                        "  display: inline-block;\n"
                                        "  font-size: 16px;\n"
                                        "  margin: 4px 2px;\n"
                                        "  transition-duration: 0.4s;\n"
                                        "  cursor: pointer;\n"
                                        "}\n"
                                        "QPushButton#ButtonHome:pressed{\n"
                                        " background-color: white; \n"
                                        "  color: black; \n"
                                        "  border: 3px solid #4CAF50;\n"
                                        "}\n"
                                        "QPushButton#ButtonHome:hover {background-color:      #d1e0e0;}")
        self.ButtonHome.setObjectName("ButtonHome")
        self.ButtonNuovoOrdine = QtWidgets.QPushButton(self)
        self.ButtonNuovoOrdine.setGeometry(QtCore.QRect(610, 110, 111, 70))
        self.ButtonNuovoOrdine.setStyleSheet("QPushButton#ButtonNuovoOrdine{\n"
                                                "  background-color:#293d3d;\n"
                                                "  border-radius: 30px;\n"
                                                "  color: white;\n"
                                                "  padding: 16px 32px;\n"
                                                "  text-align: center;\n"
                                                "  text-decoration: none;\n"
                                                "  display: inline-block;\n"
                                                "  font-size: 16px;\n"
                                                "  margin: 4px 2px;\n"
                                                "  transition-duration: 0.4s;\n"
                                                "  cursor: pointer;\n"
                                                "}\n"
                                                "QPushButton#ButtonNuovoOrdine:pressed{\n"
                                                " background-color: white; \n"
                                                "  color: black; \n"
                                                "  border: 3px solid #4CAF50;\n"
                                                "}\n"
                                                "QPushButton#ButtonNuovoOrdine:hover {background-color:      #d1e0e0;}")
        self.ButtonNuovoOrdine.setObjectName("ButtonNuovoOrdine")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("VistaListaOrdini", "Form"))
        self.ButtonApri.setText(_translate("VistaListaOrdini", "Apri"))
        self.ButtonHome.setText(_translate("VistaListaOrdini", ""))
        self.ButtonNuovoOrdine.setText(_translate("VistaListaOrdini", "Nuovo"))
