# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vistaprenotazione.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

import imaginePrenotazione

class VistaListaPrenotazioni(QWidget):
    def __init__(self, parent=None):
        super(VistaListaPrenotazioni, self).__init__()

        self.setObjectName("VistaListaPrenotazioni")
        self.resize(730, 600)
        self.setMinimumSize(QtCore.QSize(730, 600))
        self.setMaximumSize(QtCore.QSize(730, 600))

        self.sfondolistaprenotazione = QtWidgets.QLabel(self)
        self.sfondolistaprenotazione.setGeometry(QtCore.QRect(0, 0, 730, 600))
        self.sfondolistaprenotazione.setText("")
        self.sfondolistaprenotazione.setPixmap(QtGui.QPixmap(":/newPrefix/imagine.jpeg"))
        self.sfondolistaprenotazione.setScaledContents(True)
        self.sfondolistaprenotazione.setObjectName("sfondolistaprenotazione")

        self.listView = QtWidgets.QListView(self)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QtCore.QRect(30, 40, 571, 521))

        self.buttonApri = QtWidgets.QPushButton(self)
        self.buttonApri.setGeometry(QtCore.QRect(610, 40, 111, 70))
        self.buttonApri.setStyleSheet("QPushButton#buttonApri{\n"
                                        "  background-color:#293d3d;\n"
                                        "  border-radius: 30px;\n"
                                        "  color: white;\n"
                                        "  padding: 16px 32px;\n"
                                        "  text-align: center;\n"
                                        "  text-decoration: none;\n"
                                        "  display: inline-block;\n"
                                        "  font-size: 16px;\n"
                                        "  margin: 4px 2px;\n"
                                        "  transition-duration: 0.4s;\n"
                                        "  cursor: pointer;\n"
                                        "}\n"
                                        "QPushButton#buttonApri:pressed{\n"
                                        " background-color: white; \n"
                                        "  color: black; \n"
                                        "  border: 3px solid #4CAF50;\n"
                                        "}\n"
                                        "QPushButton#buttonApri:hover {background-color:      #d1e0e0;}")
        self.buttonApri.setObjectName("buttonApri")

        self.buttonHome = QtWidgets.QPushButton(self)
        self.buttonHome.setGeometry(QtCore.QRect(610, 180, 111, 70))
        self.buttonHome.setStyleSheet("QPushButton#buttonHome{\n"
                                        "  background-color:#293d3d;\n"
                                        "  border-radius: 30px;\n"
                                        "  color: white;\n"
                                        "  padding: 16px 32px;\n"
                                        "  text-align: center;\n"
                                        "  text-decoration: none;\n"
                                        "  display: inline-block;\n"
                                        "  font-size: 16px;\n"
                                        "  margin: 4px 2px;\n"
                                        "  transition-duration: 0.4s;\n"
                                        "  cursor: pointer;\n"
                                        "}\n"
                                        "QPushButton#buttonHome:pressed{\n"
                                        " background-color: white; \n"
                                        "  color: black; \n"
                                        "  border: 3px solid #4CAF50;\n"
                                        "}\n"
                                        "QPushButton#buttonHome:hover {background-color:      #d1e0e0;}")
        self.buttonHome.setObjectName("buttonHome")

        self.buttonNuovprenotazione = QtWidgets.QPushButton(self)
        self.buttonNuovprenotazione.setGeometry(QtCore.QRect(610, 110, 111, 70))
        self.buttonNuovprenotazione.setStyleSheet("QPushButton#buttonNuovprenotazione{\n"
                                                    "  background-color:#293d3d;\n"
                                                    "  border-radius: 30px;\n"
                                                    "  color: white;\n"
                                                    "  padding: 16px 32px;\n"
                                                    "  text-align: center;\n"
                                                    "  text-decoration: none;\n"
                                                    "  display: inline-block;\n"
                                                    "  font-size: 16px;\n"
                                                    "  margin: 4px 2px;\n"
                                                    "  transition-duration: 0.4s;\n"
                                                    "  cursor: pointer;\n"
                                                    "}\n"
                                                    "QPushButton#buttonNuovprenotazione:pressed{\n"
                                                    " background-color: white; \n"
                                                    "  color: black; \n"
                                                    "  border: 3px solid #4CAF50;\n"
                                                    "}\n"
                                                    "QPushButton#buttonNuovprenotazione:hover {background-color:      #d1e0e0;}")
        self.buttonNuovprenotazione.setObjectName("buttonNuovprenotazione")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("VistaListaPrenotazioni", "Form"))
        self.buttonApri.setText(_translate("VistaListaPrenotazioni", "Apri"))
        self.buttonHome.setText(_translate("VistaListaPrenotazioni", ""))
        self.buttonNuovprenotazione.setText(_translate("VistaListaPrenotazioni", "Nuova"))

