# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_self.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import QSize, QRect
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QListView
from PyQt5 import QtCore, QtGui, QtWidgets

from dipendente.views.VistaDipendente import VistaDipendente
from listadipendenti.controller.ControlloreListaDipendenti import ControlloreListaDipendenti
from listadipendenti.views.VistaInserisciDipendente import VistaInserisciDipendente
import images2

class VistaListaDipendenti(QWidget):
    def __init__(self, parent=None):
        super(VistaListaDipendenti, self).__init__(parent)

        self.controller = ControlloreListaDipendenti()

        self.setObjectName("VistaListaDipendenti")
        self.resize(730, 600)
        self.setMinimumSize(QSize(730, 600))
        self.setMaximumSize(QSize(730, 600))

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(0, 0, 730, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/textureDipendente.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        h_layout = QHBoxLayout()
        self.list_view = QListView(self)
        self.list_view.setGeometry(QRect(20, 80, 500, 450))
        self.list_view.setObjectName("listWidget")
        self.update_ui()
        h_layout.addWidget(self.list_view)



        #buttons_layout = QVBoxLayout()
        #open_button = QPushButton('Apri')
        #open_button.clicked.connect(self.show_selected_info)
        #buttons_layout.addWidget(open_button)
        #new_button = QPushButton("Nuovo")
        #new_button.clicked.connect(self.show_new_dipendente)
        #buttons_layout.addWidget(new_button)
        #buttons_layout.addStretch()
        #h_layout.addLayout(buttons_layout)
        self.Button_ApriDipendente = QtWidgets.QPushButton(self)
        self.Button_ApriDipendente.setGeometry(QtCore.QRect(550, 80, 150, 70))
        self.Button_ApriDipendente.setStyleSheet("QPushButton#Button_ApriDipendente{\n"
                                                 "  background-color:#293d3d;\n"
                                                 "  border-radius: 30px;\n"
                                                 "  color: white;\n"
                                                 "  padding: 16px 32px;\n"
                                                 "  text-align: center;\n"
                                                 "  text-decoration: none;\n"
                                                 "  display: inline-block;\n"
                                                 "  font-size: 16px;\n"
                                                 "  margin: 4px 2px;\n"
                                                 "  transition-duration: 0.4s;\n"
                                                 "  cursor: pointer;\n"
                                                 "}\n"
                                                 "QPushButton#Button_ApriDipendente:pressed{\n"
                                                 " background-color: white; \n"
                                                 "  color: black; \n"
                                                 "  border: 3px solid #4CAF50;\n"
                                                 "}\n"
                                                 "QPushButton#Button_ApriDipendente:hover {background-color:      #d1e0e0;}\n"
                                                 "")
        self.Button_ApriDipendente.setObjectName("Button_ApriDipendente")


        self.Button_NuovoDipendente = QtWidgets.QPushButton(self)
        self.Button_NuovoDipendente.setGeometry(QtCore.QRect(550, 160, 150, 70))
        self.Button_NuovoDipendente.setStyleSheet("QPushButton#Button_NuovoDipendente{\n"
                                                  "  background-color:#293d3d;\n"
                                                  "  border-radius: 30px;\n"
                                                  "  color: white;\n"
                                                  "  padding: 16px 32px;\n"
                                                  "  text-align: center;\n"
                                                  "  text-decoration: none;\n"
                                                  "  display: inline-block;\n"
                                                  "  font-size: 16px;\n"
                                                  "  margin: 4px 2px;\n"
                                                  "  transition-duration: 0.4s;\n"
                                                  "  cursor: pointer;\n"
                                                  "}\n"
                                                  "QPushButton#Button_NuovoDipendente:pressed{\n"
                                                  " background-color: white; \n"
                                                  "  color: black; \n"
                                                  "  border: 3px solid #4CAF50;\n"
                                                  "}\n"
                                                  "QPushButton#Button_NuovoDipendente:hover {background-color:      #d1e0e0;}")
        self.Button_NuovoDipendente.setObjectName("Button_NuovoDipendente")

        self.Button_Home = QtWidgets.QPushButton(self)
        self.Button_Home.setGeometry(QtCore.QRect(550, 240, 150, 70))
        #font = QtGui.QFont()
        #font.setFamily("HoloLens MDL2 Assets")
        #font.setPointSize(-1)
        #font.setUnderline(False)
        #font.setStrikeOut(False)
       # self.Button_Home.setFont(font)
        self.Button_Home.setStyleSheet("QPushButton#Button_Home{\n"
                                       "  background-color:#293d3d;\n"
                                       "  border-radius: 30px;\n"
                                       "  color: white;\n"
                                       "  padding: 16px 32px;\n"
                                       "  text-align: center;\n"
                                       "  text-decoration: none;\n"
                                       "  display: inline-block;\n"
                                       "  font-size: 20px;\n"
                                       "  margin: 4px 2px;\n"
                                       "  transition-duration: 0.4s;\n"
                                       "  cursor: pointer;\n"
                                       "}\n"
                                       "QPushButton#Button_Home:pressed{\n"
                                       " background-color: white; \n"
                                       "  color: black; \n"
                                       "  border: 3px solid #4CAF50;\n"
                                       "}\n"
                                       "QPushButton#Button_Home:hover {background-color:      #d1e0e0;}\n"
                                       "")
        self.Button_Home.setObjectName("Button_Home")

        self.Button_ApriDipendente.clicked.connect(self.show_selected_info)
        self.Button_NuovoDipendente.clicked.connect(self.show_new_dipendente)
        self.Button_Home.clicked.connect(self.close)

      #  self.setLayout(h_layout)
     #   self.resize(500,200)
      #  self.setWindowTitle('Lista Dipendenti')

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def update_ui(self):
        self.listview_model = QStandardItemModel(self.list_view)
        for dipendente in self.controller.get_lista_dipendenti():
            item = QStandardItem()
            item.setText(dipendente.nome + " " + dipendente.cognome)
            item.setEditable(False)
            font = item.font()
            font.setPointSize(18)
            item.setFont(font)
            self.listview_model.appendRow(item)
        self.list_view.setModel(self.listview_model)

    def show_selected_info(self):
        if(len(self.list_view.selectedIndexes()) > 0):
            selected = self.list_view.selectedIndexes()[0].row()
            dipendente_selezionato = self.controller.get_dipendente_by_index(selected)
            self.vista_dipendente = VistaDipendente(dipendente_selezionato, self.controller.elimina_dipendente_by_id, self.update_ui)
            self.vista_dipendente.show()

    def show_new_dipendente(self):
        self.vista_inserisci_dipendente = VistaInserisciDipendente(self.controller, self.update_ui)
        self.vista_inserisci_dipendente.show()

    def closeEvent(self, event):
        self.controller.save_data()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("VistaListaDipendenti", "Form"))
        self.Button_ApriDipendente.setText(_translate("VistaListaDipendenti", "Apri"))
        self.Button_NuovoDipendente.setText(_translate("VistaListaDipendenti", "Nuovo"))
        self.Button_Home.setText(_translate("VistaListaDipendenti", ""))